name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      MONGO_URI: mongodb://localhost:27017
      DB_NAME: te_reo_test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pytest pytest-asyncio pytest-env pytest-dotenv

      - name: Wait for MongoDB to be healthy
        run: |
          until mongosh --quiet --eval "db.adminCommand({ ping: 1 })"; do
            echo "Waiting for MongoDB…"
            sleep 2
          done

      - name: Run tests
        run: |
          pytest -q --disable-warnings --maxfail=1
