name: CI Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  test_server:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    env:
      FASTAPI_ENV: test
      MONGO_URI: mongodb://localhost:27017
      DB_NAME: te_reo_test_db

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Wait for MongoDB to be ready
        run: python scripts/wait_for_mongo.py

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1
