name: CI Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  test_server:
    runs-on: ubuntu-latest

    # Start MongoDB service
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    # Tell your app it's in test mode and point at the test DB
    env:
      FASTAPI_ENV: test
      MONGO_URI: mongodb://localhost:27017
      DB_NAME: te_reo_test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt -r server/dev-requirements.txt

      - name: Wait for MongoDB to be ready
        run: |
          until mongo --quiet --eval "db.adminCommand({ ping: 1 })"; do
            echo "Waiting for MongoDB…"
            sleep 2
          done

      - name: Run tests
        run: pytest server/tests -q --disable-warnings --maxfail=1
